name: Test Code
run-name: ${{ github.actor }} triggered Test Code Workflow
on:
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    name: Test Code Job
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'corretto'
            cache: 'maven'
      - name: Build and Test Code
        run: mvn test
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/surefire-reports/**/*.txt